# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  resolvers:
    profile_photos:
      web_path:
        # use %kernel.project_dir%/web for Symfony prior to 4.0.0
        web_root: "%kernel.project_dir%/public"
        cache_prefix: "media/cache"
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    cache: ~
    home_thumb:
      quality: 75
      filters:
        fixed:
          width: 902
          height: 1302
    details_project_image:
      filters:
        relative_resize: { widen: 1260 }
    details_project_image_blur:
      quality: 50
      filters:
        relative_resize: { widen: 2000 }
